spring.application.name=calculator-service
base.rate=15
insurance.percentage=2.5
minimum.threshold.salary=22000
minimum.rate.adjustment=1
small.rate.adjustment=2
medium.rate.adjustment=3
big.rate.adjustment=5