openapi: 3.0.0
info:
  title: Loan Calculator API
  description: API for calculating loan parameters and offers
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /calculator/offers:
    post:
      tags:
        - Calculator
      summary: Gets loan offers
      description: Gets loan offers with all possible combinations of parameters by info from LoanStatementRequest
      operationId: getOffers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanStatementRequest'
      responses:
        '200':
          description: Loan offers successfully generated
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LoanOffer'
        '400':
          description: Invalid data

  /calculator/calc:
    post:
      tags:
        - Calculator
      summary: Gets credit
      description: Gets parameters for credit by info from ScoringData
      operationId: getCredit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScoringData'
      responses:
        '200':
          description: Credit calculated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credit'
        '500':
          description: Loan denied

components:
  schemas:
    PaymentScheduleElement:
      type: object
      properties:
        number:
          type: integer
          description: Payment number
          example: 4
        date:
          type: string
          format: date
          description: Date of payment
          example: "2025-04-18"
        totalPayment:
          type: number
          format: double
          description: Total payment amount
          example: 10500
        interestPayment:
          type: number
          format: double
          description: Interest part of the payment
          example: 500
        debtPayment:
          type: number
          format: double
          description: Main part of the payment
          example: 10000
        remainingDebt:
          type: number
          format: double
          description: Remaining debt after payment
          example: 160000

    Employment:
      type: object
      properties:
        employmentStatus:
          type: string
          description: Employment status of client
          enum: [UNEMPLOYED, SELF_EMPLOYED, EMPLOYED, BUSINESS_OWNER]
          example: EMPLOYED
        employerINN:
          type: string
          description: Taxpayer identification number of client's employer
          example: "520205004556"
        salary:
          type: number
          format: double
          description: Size of client's salary
          example: 40000
        position:
          type: string
          description: Position at work
          enum: [WORKER, MID_MANAGER, TOP_MANAGER, OWNER]
          example: WORKER
        workExperienceTotal:
          type: integer
          description: Total work experience, number of months
          example: 36
        workExperienceCurrent:
          type: integer
          description: Current work experience, number of months
          example: 24

    LoanStatementRequest:
      type: object
      required:
        - amount
        - term
        - firstName
        - lastName
        - email
        - birthdate
        - passportSeries
        - passportNumber
      properties:
        amount:
          type: number
          format: double
          minimum: 10000
          maximum: 100000000
          description: Requested loan amount
          example: 200000
        term:
          type: integer
          minimum: 3
          maximum: 360
          description: Loan term, number of months
          example: 24
        firstName:
          type: string
          pattern: '^[a-zA-Zа-яёА-ЯЁ-]{1,60}$'
          description: First name of client
          example: Ivan
        lastName:
          type: string
          pattern: '^[a-zA-Zа-яёА-ЯЁ-]{1,60}$'
          description: Last name of client
          example: Ivanov
        middleName:
          type: string
          pattern: '^$|^[a-zA-Zа-яёА-ЯЁ-]{1,60}$'
          description: Middle name of client
          example: Ivanovich
        email:
          type: string
          pattern: '^[a-z0-9A-Z_!#$%&''*+/=?`{|}~^.-]+@[a-z0-9A-Z.-]+$'
          description: Email of client
          example: ivan@mail.ru
        birthdate:
          type: string
          format: date
          description: Date of birth of client
          example: "2000-01-01"
        passportSeries:
          type: string
          pattern: '^[0-9]{4}$'
          description: Passport series of client
          example: "6060"
        passportNumber:
          type: string
          pattern: '^[0-9]{6}$'
          description: Passport number of client
          example: "473058"

    Credit:
      type: object
      properties:
        amount:
          type: number
          format: double
          description: Requested loan amount
          example: 200000
        term:
          type: integer
          description: Loan term, number of months
          example: 24
        monthlyPayment:
          type: number
          format: double
          description: The amount of payment for every month
          example: 10000
        rate:
          type: number
          format: double
          description: Loan rate calculated depending on parameters, percentages
          example: 22
        psk:
          type: number
          format: double
          description: Total cost of credit
          example: 250000
        isInsuranceEnabled:
          type: boolean
          description: Information about whether insurance is included
          example: true
        isSalaryClient:
          type: boolean
          description: Information about whether the client is a salary client
          example: false
        paymentSchedule:
          type: array
          description: Payment schedule in the form of a list of elements with info about each payment
          items:
            $ref: '#/components/schemas/PaymentScheduleElement'
          example:
            - number: 1
              date: "2025-01-01"
              totalPayment: 10500
              interestPayment: 500
              debtPayment: 10000
              remainingDebt: 190000
            - number: 2
              date: "2025-02-01"
              totalPayment: 10400
              interestPayment: 490
              debtPayment: 10000
              remainingDebt: 180000

    ScoringData:
      type: object
      properties:
        amount:
          type: number
          format: double
          description: Requested loan amount
          example: 200000
        term:
          type: integer
          description: Loan term, number of months
          example: 24
        firstName:
          type: string
          description: First name of client
          example: Ivan
        lastName:
          type: string
          description: Last name of client
          example: Ivanov
        middleName:
          type: string
          description: Middle name of client
          example: Ivanovich
        gender:
          type: string
          description: Gender of client
          enum: [MALE, FEMALE, NON_BINARY]
          example: MALE
        birthdate:
          type: string
          format: date
          description: Date of birth of client
          example: "2000-01-01"
        passportSeries:
          type: string
          description: Passport series of client
          example: "6060"
        passportNumber:
          type: string
          description: Passport number of client
          example: "473058"
        passportIssueDate:
          type: string
          format: date
          description: Date of issue of the client's passport
          example: "2021-01-15"
        passportIssueBranch:
          type: string
          description: Client's passport issuing department
          example: "Passport issuance department of the federal migration service for the saratov region"
        maritalStatus:
          type: string
          description: Gender of client
          enum: [MARRIED, DIVORCED, SINGLE, WIDOW_WIDOWER]
          example: SINGLE
        dependentAmount:
          type: integer
          description: Number of client's dependents
          example: 0
        employment:
          $ref: '#/components/schemas/Employment'
        accountNumber:
          type: string
          description: Client's account number
          example: "3567890"
        isInsuranceEnabled:
          type: boolean
          description: Information about whether insurance is included
          example: true
        isSalaryClient:
          type: boolean
          description: Information about whether the client is a salary client
          example: false

    LoanOffer:
      type: object
      properties:
        statementId:
          type: string
          format: uuid
          description: Unique id of loan statement
          example: "647s37fb890d03s499g8"
        requestedAmount:
          type: number
          format: double
          description: Requested loan amount
          example: 200000
        totalAmount:
          type: number
          format: double
          description: Total loan amount
          example: 250000
        term:
          type: integer
          description: Loan term, number of months
          example: 24
        monthlyPayment:
          type: number
          format: double
          description: The amount of payment for every month
          example: 10000
        rate:
          type: number
          format: double
          description: Loan rate calculated depending on parameters, percentages
          example: 22
        isInsuranceEnabled:
          type: boolean
          description: Information about whether insurance is included
          example: true
        isSalaryClient:
          type: boolean
          description: Information about whether the client is a salary client
          example: false