server:
  port: 8081
spring:
  application:
    name: deal-service

  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/changelog.xml
    enabled: true

code:
  length: 6

topic:
  finish-registration: finish-registration
  create-documents: create-documents
  send-documents: send-documents
  send-ses: send-ses
  credit-issued: credit-issued
  statement-denied: statement-denied