server:
  port: 8081
spring:
  application:
    name: deal-service

  datasource:
    url: jdbc:postgresql://localhost:5432/credit_bank_deal_service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

app:
  gateway:
    uri: http://localhost:8080
  calculator:
    offers: /calculator/offers
    credit: /calculator/calc